//FILTERS
export const FILTER_BY_PROFESSION = 'FILTER_BY_PROFESSION';
export const FILTER_BY_NAME =       'FILTER_BY_NAME';

//INHABITANTS
export const INHABITANTS_LOAD_DATA = 'INHABITANTS_LOAD_DATA';
export const INHABITANTS_LOAD_ERROR = 'INHABITANTS_LOAD_ERROR';